- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repo.d/momgodb.repo

  - name: install mangodb
    ansible.builtin.package:
       name: mogodb-org
       state: present

  - name: start and enable mogodb
    ansible.builtin.service:
       name: mongod
       state: started
       enabled: yes

  - name: allow remote connections 
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: restart
